### ISSUE TITLE
Charts are not shown on Openhab Android APP

### ISSUE THREAD

**Issue by marcolino7** [wborn/smarthome-grafana#4]
Hi,
I'm using your code in my openhab installation. Works like a charm from the browser but not on Android app.
I tried to include in sitemap direct grafana link, and it work, so I think there is someting in your code that avoid charts to be shown on android app.

Can you helpme about this?

Kindly regarda
Marco

**Comment by wborn** [comment]
@marcolino7 I've added a comment in [issue #2](https://github.com/wborn/smarthome-grafana/issues/2#issuecomment-276238346) with some details on how to get the code with charts working in the openHAB Android App. Hopefully that works out well for you too!

**Comment by marcolino7** [comment]
HI,
I make it work.
Thanks

**Comment by wborn** [comment]
That's great!
